apiVersion: v1
kind: DeploymentConfig
metadata:
  name: restful-nodejs
  namespace: {{PROJECT}}
  labels:
    app: restful-nodejs
spec:
  replicas: 1
  selector:
      app: restful-nodejs
  template:
    metadata:
      labels:
        app: restful-nodejs
    spec:
      containers:
      - name: restful-nodejs
        image: nexus.esc.yipintsoigroup.com/restful-nodejs:{{TAG_IMAGE}}
        ports:
        - containerPort: 8081
      imagePullSecrets:
        - name: nexus